const menus = [
  {
    id: 'ewManagement',
    name: '二网管理',
    link: 'ewManagement',
    icon: 'team',
    subMenu: [
      {
        id: 'primaryAudit',
        name: '二网初审',
        link: 'primaryAudit',
        parentId: 'ewManagement',
      },
      {
        id: 'lastAudit',
        name: '二网复审',
        link: 'lastAudit',
        parentId: 'ewManagement',
      },
    ],
  },
  {
    id: 'bondManagement',
    name: '保证金管理',
    link: 'bondManagement',
    icon: 'pay-circle',
    subMenu: [
      {
        id: 'transferIn',
        name: '转入审批表',
        link: 'transferIn',
        parentId: 'bondManagement',
      },
      {
        id: 'transferOut',
        name: '转出审批表',
        link: 'transferOut',
        parentId: 'bondManagement',
      },
      {
        id: 'printManagement',
        name: '保证金打印管理',
        link: 'printManagement',
        parentId: 'bondManagement',
      },
      {
        id: 'confirmReceiptList',
        name: '确认回执列表',
        link: 'confirmReceiptList',
        parentId: 'bondManagement',
      },
    ],
  },
  {
    id: 'yqzlManagement',
    name: '银企直联',
    link: 'yqzlManagement',
    icon: 'form',
    subMenu: [
      {
        id: 'carStatistics',
        name: '车辆录入统计-大连',
        link: 'carStatistics',
        parentId: 'yqzlManagement',
      },
      {
        id: 'carChengType',
        name: '橙E格式-新',
        link: 'carChengType',
        parentId: 'yqzlManagement',
      },
      {
        id: 'carSystemType',
        name: '系统格式-新',
        link: 'carSystemType',
        parentId: 'yqzlManagement',
      },
      {
        id: 'carReturnType',
        name: '车辆赎回-新',
        link: 'carReturnType',
        parentId: 'yqzlManagement',
      },
      {
        id: 'carSync',
        name: '数据同步',
        link: 'carSync',
        parentId: 'yqzlManagement',
      },
      {
        id: 'CarAction_Dis',
        name: '车辆明细上报',
        link: 'CarAction_Dis',
        parentId: 'yqzlManagement',
      },
      {
        id: 'CarAction_Bank',
        name: '车辆明细汇总',
        link: 'CarAction_Bank',
        parentId: 'yqzlManagement',
      },
      {
        id: 'noSuperviseList',
        name: '税控监管抽查明细',
        link: 'noSuperviseList',
        parentId: 'yqzlManagement',
      },
      {
        id: 'noSuperviseBatch',
        name: '批量下发任务-税控监管',
        link: 'noSuperviseBatch',
        parentId: 'yqzlManagement',
      },
    ],
  },
  {
    id: 'StatementFCZ',
    name: '放车组报表',
    link: 'StatementFCZ',
    icon: 'form',
    subMenu: [
      {
        id: 'settingFCZ',
        name: '参数设置',
        link: 'settingFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'uploadFCZ',
        name: '数据源导入',
        link: 'uploadFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'carCollectFCZ',
        name: '车辆汇总表',
        link: 'carCollectFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'ledgerFCZ',
        name: '台账下载',
        link: 'ledgerFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'policyFCZ',
        name: '差异化政策汇总管理',
        link: 'policyFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'dealerFCZ',
        name: '税控监管名单',
        link: 'dealerFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'usedCarFCZ',
        name: '二手车车辆明细',
        link: 'usedCarFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'supervisorFCZ',
        name: '经销商-监管方管理',
        link: 'supervisorFCZ',
        parentId: 'StatementFCZ',
      },
      {
        id: 'daoqiFCZ',
        name: '到期票提示',
        link: 'daoqiFCZ',
        parentId: 'StatementFCZ',
      },
    ],
  },
  {
    id: 'ledgerManagement',
    name: '台账管理',
    link: 'ledgerManagement',
    icon: 'form',
    subMenu: [
      {
        id: 'ewDetail',
        name: '二网明细台账',
        link: 'ewDetail',
        parentId: 'ledgerManagement',
      },
      {
        id: 'disBond',
        name: '经销商保证金汇总台账',
        link: 'disBond',
        parentId: 'ledgerManagement',
      },
      {
        id: 'disDeposit',
        name: '经销商保证金本金汇总台账',
        link: 'disDeposit',
        parentId: 'ledgerManagement',
      },
      {
        id: 'ewBond',
        name: '二网保证金汇总台账',
        link: 'ewBond',
        parentId: 'ledgerManagement',
      },
      {
        id: 'bondDetail',
        name: '二网保证金明细台账',
        link: 'bondDetail',
        parentId: 'ledgerManagement',
      },
      {
        id: 'ewOnlineList',
        name: '二网上线情况汇总',
        link: 'ewOnlineList',
        parentId: 'ledgerManagement',
      },
      {
        id: 'ewOnlineDetail',
        name: '二网上线情况明细',
        link: 'ewOnlineDetail',
        parentId: 'ledgerManagement',
      },
      {
        id: 'taskSummary',
        name: '任务统计',
        link: 'taskSummary',
        parentId: 'ledgerManagement',
      },
      {
        id: '台账管理',
        name: '抽查任务管理台账',
        link: 'spottestAuditLedger',
        parentId: 'ledgerManagement',
      },
      {
        id: 'spotMove',
        name: '抽查／移动情况统计表',
        link: 'spotMove',
        parentId: 'ledgerManagement',
      },
      {
        id: 'ewCharge',
        name: '二网明细台账-财务专用',
        link: 'ewCharge',
        parentId: 'ledgerManagement',
      },
      {
        id: 'noSupervise',
        name: '税控监管任务台账',
        link: 'noSupervise',
        parentId: 'ledgerManagement',
      },
    ],
  },
  {
    id: 'carManagement',
    name: '车辆管理',
    link: 'carManagement',
    icon: 'car',
    subMenu: [
      {
        id: 'carSearchEngine',
        name: '工作台',
        link: 'carSearchEngine',
        parentId: 'carManagement',
      },
      {
        id: 'antiCheat',
        name: '防作弊检查',
        link: 'antiCheat',
        parentId: 'carManagement',
      },
      {
        id: 'listUnsupervised',
        name: '撤监管车辆处理',
        link: 'listUnsupervised',
        parentId: 'carManagement',
      },
    ],
  },
  {
    id: 'carCheckup',
    name: '车辆抽查',
    link: 'carCheckup',
    icon: 'car',
    subMenu: [
      {
        id: 'spottestAudit',
        name: '抽查任务管理',
        link: 'spottestAudit',
        parentId: 'carCheckup',
      },
      {
        id: 'keyPointSpot',
        name: '重点关注企业抽查',
        link: 'keyPointSpot',
        parentId: 'carCheckup',
      },
      {
        id: 'spotEwBlack',
        name: '自动审核黑名单',
        link: 'spotEwBlack',
        parentId: 'carCheckup',
      },
      {
        id: 'noSpotCar',
        name: '超20天未查车辆',
        link: 'noSpotCar',
        parentId: 'carCheckup',
      },
    ],
  },
  {
    id: 'userInfoManagement',
    name: '用户信息管理',
    link: 'userInfoManagement',
    icon: 'user',
    subMenu: [
      {
        id: 'dealerList',
        name: '经销商信息',
        link: 'dealerList',
        parentId: 'userInfoManagement',
      },
      {
        id: 'ewList',
        name: '二网信息',
        link: 'ewList',
        parentId: 'userInfoManagement',
      },
      {
        id: 'repoAuditFirst',
        name: '仓库审核-初审',
        link: 'repoAuditFirst',
        parentId: 'userInfoManagement',
      },
      {
        id: 'repoAuditLast',
        name: '仓库审核-复审',
        link: 'repoAuditLast',
        parentId: 'userInfoManagement',
      },
      {
        id: 'clientManagement',
        name: '终端管理',
        link: 'clientManagement',
        parentId: 'userInfoManagement',
      },
      {
        id: 'cameraList',
        name: '摄像头管理',
        link: 'cameraList',
        parentId: 'userInfoManagement',
      },
    ],
  },
  {
    id: 'carFactoryManagement',
    name: '汽车厂商管理',
    link: 'carFactoryManagement',
    icon: 'crown',
    subMenu: [
      {
        id: 'carMoving',
        name: '移车点检表',
        link: 'carMoving',
        parentId: 'carFactoryManagement',
      },
      {
        id: 'checkedDetail',
        name: '点检明细表',
        link: 'checkedDetail',
        parentId: 'carFactoryManagement',
      },
      {
        id: 'CarSales',
        name: '车型销量表',
        link: 'CarSales',
        parentId: 'carFactoryManagement',
      },
      {
        id: 'dealerSaleRink',
        name: '经销商销量排名',
        link: 'dealerSaleRink',
        parentId: 'carFactoryManagement',
      },
      {
        id: 'ewSaleRink',
        name: '二网销量排名',
        link: 'ewSaleRink',
        parentId: 'carFactoryManagement',
      },
      {
        id: 'regionManagement',
        name: '大区设置',
        link: 'regionManagement',
        parentId: 'carFactoryManagement',
      },
    ],
  },
  {
    id: 'exceptionManagement',
    name: '异常管理',
    link: 'exceptionManagement',
    icon: 'warning',
    subMenu: [
      {
        id: 'spotException',
        name: '抽查异常管理',
        link: 'spotException',
        parentId: 'exceptionManagement',
      },
      {
        id: 'movingException',
        name: '移动异常管理',
        link: 'movingException',
        parentId: 'exceptionManagement',
      },
      {
        id: 'carBillContrast',
        name: '赎车-开票数据比对',
        link: 'carBillContrast',
        parentId: 'exceptionManagement',
      },
    ],
  },
  {
    id: 'systemManagement',
    name: '系统管理',
    link: 'systemManagement',
    icon: 'setting',
    subMenu: [
      {
        id: 'multipleAccount',
        name: '综合账号管理',
        link: 'multipleAccount',
        parentId: 'systemManagement',
      },
    ],
  },
  {
    id: 'monitorManagement',
    name: '二库视频监控',
    link: 'monitorManagement',
    icon: 'video-camera',
    subMenu: [
      {
        id: 'repositoryList',
        name: '库存车监控',
        link: 'repositoryList',
        parentId: 'monitorManagement',
      },
      {
        id: 'repositoryWarning',
        name: '库存数量预警',
        link: 'repositoryWarning',
        parentId: 'monitorManagement',
      },
    ],
  },
  {
    id: 'miniProgramBackEndManagement',
    name: '小程序后台管理',
    link: 'miniProgramBackEndManagement',
    icon: 'wechat',
    subMenu: [
      {
        id: 'orderManagement',
        name: '订单管理',
        link: 'orderManagement',
        parentId: 'miniProgramBackEndManagement',
      },
      {
        id: 'invoiceManagement',
        name: '开票管理',
        link: 'invoiceManagement',
        parentId: 'miniProgramBackEndManagement',
      },
      {
        id: 'refundManagement',
        name: '退款确认',
        link: 'refundManagement',
        parentId: 'miniProgramBackEndManagement',
      },
    ],
  },
  {
    id: 'superviseManagement',
    name: '监管公司抽查管理',
    link: 'superviseManagement',
    icon: 'check-circle',
    subMenu: [
      {
        id: 'importView',
        name: '库存明细导入',
        link: 'importView',
        parentId: 'superviseManagement',
      },
      {
        id: 'superviseManager',
        name: '抽查管理',
        link: 'superviseManager',
        parentId: 'superviseManagement',
      },
      {
        id: 'superviseAmount',
        name: '抽查记录统计',
        link: 'superviseAmount',
        parentId: 'superviseManagement',
      },
      {
        id: 'superviseCompany',
        name: '监管公司',
        link: 'superviseCompany',
        parentId: 'superviseManagement',
      },
      {
        id: 'specialDealer',
        name: '特殊抽查名单',
        link: 'specialDealer',
        parentId: 'superviseManagement',
      },
      {
        id: 'superviseParam',
        name: '参数设置',
        link: 'superviseParam',
        parentId: 'superviseManagement',
      },
    ],
  },
  {
    id: 'selfCarManagement',
    name: '自有车管理',
    link: 'selfCarManagement',
    icon: 'dashboard',
    subMenu: [
      {
        id: 'excUploadAll',
        name: '车辆全量导入',
        link: 'excUploadAll',
        parentId: 'selfCarManagement',
      },
      {
        id: 'excUploadAdd',
        name: '车辆增量导入',
        link: 'excUploadAdd',
        parentId: 'selfCarManagement',
      },
      {
        id: 'selfCarMgPage',
        name: '车辆管理',
        link: 'selfCarMgPage',
        parentId: 'selfCarManagement',
      },
      {
        id: 'commonTask',
        name: '抽查任务',
        link: 'commonTask',
        parentId: 'selfCarManagement',
      },
      {
        id: 'movingTask',
        name: '移动任务',
        link: 'movingTask',
        parentId: 'selfCarManagement',
      },
      {
        id: 'certificateTask',
        name: '盘证任务',
        link: 'certificateTask',
        parentId: 'selfCarManagement',
      },
      {
        id: 'soldConfirm',
        name: '已售确认',
        link: 'soldConfirm',
        parentId: 'selfCarManagement',
      },
      {
        id: 'moveRecord',
        name: '移动记录',
        link: 'moveRecord',
        parentId: 'selfCarManagement',
      },
      {
        id: 'locaManage',
        name: '定位点管理',
        link: 'locaManage',
        parentId: 'selfCarManagement',
      },
      {
        id: 'regionalism',
        name: '区域划分',
        link: 'regionalism',
        parentId: 'selfCarManagement',
      },
      {
        id: 'selfCarBrand',
        name: '品牌管理',
        link: 'selfCarBrand',
        parentId: 'selfCarManagement',
      },
      {
        id: 'financialPro',
        name: '金融产品管理',
        link: 'financialPro',
        parentId: 'selfCarManagement',
      },
      {
        id: 'paramsSetting',
        name: '参数设置',
        link: 'paramsSetting',
        parentId: 'selfCarManagement',
      },
      {
        id: 'carPhoTemp',
        name: '车辆拍照模板',
        link: 'carPhoTemp',
        parentId: 'selfCarManagement',
      },
      {
        id: 'credPhoTemp',
        name: '证件拍照模板',
        link: 'credPhoTemp',
        parentId: 'selfCarManagement',
      },
      {
        id: 'exceSetting',
        name: '异常类型设置',
        link: 'exceSetting',
        parentId: 'selfCarManagement',
      },
      {
        id: 'standMang',
        name: '台账管理',
        link: 'standMang',
        parentId: 'selfCarManagement',
      },
      {
        id: 'selfcarCheat',
        name: '防作弊检查',
        link: 'selfcarCheat',
        parentId: 'selfCarManagement',
      },
    ],
  },
  {
    id: 'RoleManagement',
    name: '授权管理',
    link: 'RoleManagement',
    icon: 'check-circle',
    subMenu: [
      {
        id: 'storeManagement',
        name: '微店管理',
        link: 'storeManagement',
        parentId: 'RoleManagement',
      },
    ],
  },
  {
    id: 'warningInd',
    name: '预警指标',
    link: 'warningInd',
    icon: 'warning',
    subMenu: [
      {
        id: 'uploadWarning',
        name: '数据源导入',
        link: 'uploadWarning',
        parentId: 'warningInd',
      },
      {
        id: 'supplyMana',
        name: '供应链管理',
        link: 'supplyMana',
        parentId: 'warningInd',
      },
      {
        id: 'brandMana',
        name: '品牌管理',
        link: 'brandMana',
        parentId: 'warningInd',
      },
      {
        id: 'statAnalysis',
        name: '统计分析',
        link: 'statAnalysis',
        parentId: 'warningInd',
      },
      {
        id: 'warningMes',
        name: '预警信息',
        link: 'warningMes',
        parentId: 'warningInd',
      },
      {
        id: 'paraSetting',
        name: '参数设置',
        link: 'paraSetting',
        parentId: 'warningInd',
      },
      {
        id: 'warningBrandMana',
        name: '品牌合作管理',
        link: 'warningBrandMana',
        parentId: 'warningInd',
      },
      {
        id: 'repaymentAmount',
        name: '经销商销量/回款统计表',
        link: 'repaymentAmount',
        parentId: 'warningInd',
      },
    ],
  },
  {
    id: 'carMatching',
    name: '长安车-票匹配',
    link: 'carMatching',
    icon: 'car',
    subMenu: [
      {
        id: 'uploadMatch',
        name: '数据源导入',
        link: 'uploadMatch',
        parentId: 'carMatching',
      },
      {
        id: 'collectMatch',
        name: '开票汇总',
        link: 'collectMatch',
        parentId: 'carMatching',
      },
      {
        id: 'thirdMatch',
        name: '三方出库信息',
        link: 'thirdMatch',
        parentId: 'carMatching',
      },
      {
        id: 'matchList',
        name: '车辆匹配明细',
        link: 'matchList',
        parentId: 'carMatching',
      },
    ],
  },
  {
    id: 'carMatching_JF',
    name: '解放车-票匹配',
    link: 'carMatching_JF',
    icon: 'car',
    subMenu: [
      {
        id: 'uploadMatch_JF',
        name: '数据源导入',
        link: 'uploadMatch_JF',
        parentId: 'carMatching_JF',
      },
      {
        id: 'collectMatch_JF',
        name: '开票汇总',
        link: 'collectMatch_JF',
        parentId: 'carMatching_JF',
      },
      {
        id: 'thirdMatch_JF',
        name: '解放发车信息',
        link: 'thirdMatch_JF',
        parentId: 'carMatching_JF',
      },
      {
        id: 'matchList_JF',
        name: '一汽解放台账',
        link: 'matchList_JF',
        parentId: 'carMatching_JF',
      },
    ],
  },
  {
    id: 'ewMarket',
    name: '二网销售确认',
    link: 'ewMarket',
    icon: 'car',
    subMenu: [
      {
        id: 'marketList',
        name: '二网销售列表',
        link: 'marketList',
        parentId: 'ewMarket',
      },
      {
        id: 'marketFirst',
        name: '二网销售初审',
        link: 'marketFirst',
        parentId: 'ewMarket',
      },
      {
        id: 'marketRecheck',
        name: '二网销售复审',
        link: 'marketRecheck',
        parentId: 'ewMarket',
      },
      {
        id: 'marketAwardCheck',
        name: '待发放奖励审核',
        link: 'marketAwardCheck',
        parentId: 'ewMarket',
      },
      {
        id: 'marketAwardRemit',
        name: '奖励金打款',
        link: 'marketAwardRemit',
        parentId: 'ewMarket',
      },
    ],
  },
];

export const subMenuMap = {
  primaryAudit: {
    list: '',
    detail: '查看二网审批信息',
  },
  lastAudit: {
    list: '',
    detail: '查看二网审批信息',
  },
  spotException: {
    list: '',
    detail: '查看抽查异常跟踪信息',
  },
  repositoryList: {
    detail: '影像明细',
    train: '模型训练',
  },
  disDeposit: {
    list: '',
    detail: '查看',
    flow: '交易明细',
  },
  dealerList: {
    list: '',
    add: '新增',
    edit: '详情',
  },
  ewList: {
    list: '',
    add: '新增',
    edit: '详情',
  },
};

export const tabList = {
  list: [
    {
      id: 'todo',
      name: '待审核',
      link: 'todo',
      parentId: 'commonTask,movingTask,certificateTask',
    },
    {
      id: 'done',
      name: '已审核',
      link: 'done',
      parentId: 'commonTask,movingTask,certificateTask',
    },
    {
      id: 'todoList',
      name: '待审核列表',
      link: 'todoList',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'expList',
      name: '异常任务列表',
      link: 'expList',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'todoListForDistr',
      name: '经销商确认',
      link: 'todoListForDistr',
      parentId: 'primaryAudit',
    },
    {
      id: 'totalList',
      name: '全部任务列表',
      link: 'totalList',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'todo',
      name: '进行中',
      link: 'todo',
      parentId: 'spotException, movingException',
    },
    {
      id: 'done',
      name: '已完成',
      link: 'done',
      parentId: 'spotException, movingException',
    },
    {
      id: 'spotTask',
      name: '抽查任务',
      link: 'spotTask',
      parentId: 'spottestAudit, spottestAuditLedger',
    },
    {
      id: 'moveTask',
      name: '移动任务',
      link: 'moveTask',
      parentId: 'spottestAudit, spottestAuditLedger',
    },
    {
      id: 'timeOut',
      name: '超时待补拍任务',
      link: 'timeOut',
      parentId: 'spottestAudit, spottestAuditLedger',
    },
    {
      id: 'todoComplete',
      name: '已审核',
      link: 'todoComplete',
      parentId: 'spottestAudit, spottestAuditLedger',
    },
    {
      id: 'todoOrderList',
      name: '待付款',
      link: 'todoOrderList',
      parentId: 'orderManagement',
    },
    {
      id: 'doneOrderList',
      name: '已付款',
      link: 'doneOrderList',
      parentId: 'orderManagement',
    },
    {
      id: 'goneOrderList',
      name: '已失效',
      link: 'goneOrderList',
      parentId: 'orderManagement',
    },
    {
      id: 'todoInvoiceList',
      name: '待开票',
      link: 'todoInvoiceList',
      parentId: 'invoiceManagement',
    },
    {
      id: 'doneInvoiceList',
      name: '已开票',
      link: 'doneInvoiceList',
      parentId: 'invoiceManagement',
    },
    {
      id: 'dealerAmount',
      name: '经销商',
      link: 'dealerAmount',
      parentId: 'superviseAmount',
    },
    {
      id: 'vehicleAmount',
      name: '车辆',
      link: 'vehicleAmount',
      parentId: 'superviseAmount',
    },
  ],
  detail: [
    {
      id: 'authInfo',
      name: '审核信息',
      link: 'authInfo',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'bondHistory',
      name: '保证金历史',
      link: 'bondHistory',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'distributorInfo',
      name: '经销商信息',
      link: 'distributorInfo',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'ewInfo',
      name: '二网信息',
      link: 'ewInfo',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'expressInfo',
      name: '物流信息',
      link: 'expressInfo',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'trackRecord',
      name: '跟踪记录',
      link: 'trackRecord',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'authHistory',
      name: '历史审核',
      link: 'authHistory',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'excepRecord',
      name: '异常记录',
      link: 'excepRecord',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'operation',
      name: '操作日志',
      link: 'operation',
      parentId: 'primaryAudit, lastAudit',
    },
    {
      id: 'carInfo',
      name: '车辆信息',
      link: 'carInfo',
      parentId: 'spottestAudit, spottestAuditLedger',
    },
  ],
  printManagement: [
    {
      id: 'initialTransferIn',
      name: '初始转入',
      link: 'initialTransferIn',
      parentId: 'printManagement',
    },
    {
      id: 'supplementaryTransferIn',
      name: '追加转入',
      link: 'supplementaryTransferIn',
      parentId: 'printManagement',
    },
    {
      id: 'currentInit',
      name: '活期初始',
      link: 'currentInit',
      parentId: 'printManagement',
    },
    {
      id: 'currentSupplement',
      name: '活期追加',
      link: 'currentSupplement',
      parentId: 'printManagement',
    },
    {
      id: 'transferOut',
      name: '转出',
      link: 'transferOut',
      parentId: 'printManagement',
    },
    {
      id: 'transferOutHis',
      name: '导出历史',
      link: 'transferOutHis',
      parentId: 'printManagement',
    },
  ],
  result: [
    {
      id: 'carInfo',
      name: '车辆信息',
      link: 'carInfo',
      parentId: 'carSearchEngine',
    },
    {
      id: 'carTrail',
      name: '车辆轨迹',
      link: 'carTrail',
      parentId: 'carSearchEngine',
    },
    {
      id: 'currentTask',
      name: '进行中的任务',
      link: 'currentTask',
      parentId: 'carSearchEngine',
    },
    {
      id: 'taskHistory',
      name: '抽查历史',
      link: 'taskHistory',
      parentId: 'carSearchEngine',
    },
    {
      id: 'changeRecord',
      name: '变更记录',
      link: 'changeRecord',
      parentId: 'carSearchEngine',
    },
    {
      id: 'changeVin',
      name: '银行车架号变更记录',
      link: 'changeVin',
      parentId: 'carSearchEngine',
    },
  ],
  confirmReceiptList: [
    {
      id: 'todo',
      name: '待确认回执',
      link: 'todo',
      parentId: 'confirmReceiptList',
    },
    {
      id: 'all',
      name: '全部任务',
      link: 'all',
      parentId: 'confirmReceiptList',
    },
  ],
  repoAuditFirst: [
    {
      id: 'todo',
      name: '待审核',
      link: 'todo',
      parentId: 'repoAuditFirst',
    },
    {
      id: 'all',
      name: '审核历史',
      link: 'all',
      parentId: 'repoAuditFirst',
    },
  ],
  repoAuditLast: [
    {
      id: 'todo',
      name: '待审核',
      link: 'todo',
      parentId: 'repoAuditLast',
    },
    {
      id: 'all',
      name: '审核历史',
      link: 'all',
      parentId: 'repoAuditLast',
    },
  ],
  taskSummary: [
    {
      id: 'platformManager',
      name: '平台抽查员',
      link: 'platformManager',
      parentId: 'taskSummary',
    },
    {
      id: 'riskManager',
      name: '风控专员',
      link: 'riskManager',
      parentId: 'taskSummary',
    },
    {
      id: 'customerManager',
      name: '客户经理',
      link: 'customerManager',
      parentId: 'taskSummary',
    },
  ],
  repositoryWarning: [
    {
      id: 'todo',
      name: '未解除',
      link: 'todo',
      parentId: 'repositoryWarning',
    },
    {
      id: 'gone',
      name: '已解除',
      link: 'gone',
      parentId: 'repositoryWarning',
    },
  ],
  soldConfirm: [
    {
      id: 'todo',
      name: '待确认',
      link: 'todo',
      parentId: 'soldConfirm',
    },
    {
      id: 'gone',
      name: '已确认',
      link: 'gone',
      parentId: 'soldConfirm',
    },
  ],
  selfCarMgPage: [
    {
      id: 'reserved',
      name: '自有车',
      link: 'reserved',
      parentId: 'selfCarMgPage',
    },
    {
      id: 'removed',
      name: '删除历史',
      link: 'removed',
      parentId: 'selfCarMgPage',
    },
  ],
  regionalism: [
    {
      id: 'smallMang',
      name: '小区管理',
      link: 'smallMang',
      parentId: 'regionalism',
    },
    {
      id: 'bigMang',
      name: '大区管理',
      link: 'bigMang',
      parentId: 'regionalism',
    },
  ],
  excUploadAll: [
    {
      id: 'uploadAll',
      name: '导入',
      link: 'uploadAll',
      parentId: 'excUploadAll',
    },
    {
      id: 'uploadAllList',
      name: '导入记录',
      link: 'uploadAllList',
      parentId: 'excUploadAll',
    },
  ],
  excUploadAdd: [
    {
      id: 'add',
      name: '新增明细导入',
      link: 'add',
      parentId: 'excUploadAdd',
    },
    {
      id: 'sell',
      name: '出售明细导入',
      link: 'sell',
      parentId: 'excUploadAdd',
    },
    {
      id: 'list',
      name: '导入记录',
      link: 'list',
      parentId: 'excUploadAdd',
    },
  ],
  carPhoTemp: [
    {
      id: 'newCar',
      name: '新车',
      link: 'newCar',
      parentId: 'carPhoTemp',
    },
    {
      id: 'esCar',
      name: '二手车',
      link: 'esCar',
      parentId: 'carPhoTemp',
    },
  ],
  exceSetting: [
    {
      id: 'car',
      name: '抽查',
      link: 'car',
      parentId: 'exceSetting',
    },
    {
      id: 'move',
      name: '移动',
      link: 'move',
      parentId: 'exceSetting',
    },
    {
      id: 'plate',
      name: '盘证抽查',
      link: 'plate',
      parentId: 'exceSetting',
    },
  ],
  standMang: [
    {
      id: 'car',
      name: '抽查任务',
      link: 'car',
      parentId: 'standMang',
    },
    {
      id: 'plate',
      name: '盘证任务',
      link: 'plate',
      parentId: 'standMang',
    },
  ],
  credPhoTemp: [
    {
      id: 'newCar',
      name: '新车',
      link: 'newCar',
      parentId: 'credPhoTemp',
    },
    {
      id: 'esCar',
      name: '二手车',
      link: 'esCar',
      parentId: 'credPhoTemp',
    },
  ],
  storeManagement: [
    {
      id: 'distributor',
      name: '经销商微店',
      link: 'distributor',
      parentId: 'storeManagement',
    },
    {
      id: 'ew',
      name: '二网微店',
      link: 'ew',
      parentId: 'storeManagement',
    },
  ],
  uploadWarning: [
    {
      id: 'refund',
      name: '还款金额',
      link: 'refund',
      parentId: 'uploadWarning',
    },
    {
      id: 'expire',
      name: '到期票',
      link: 'expire',
      parentId: 'uploadWarning',
    },
    {
      id: 'shift',
      name: '转池台账',
      link: 'shift',
      parentId: 'uploadWarning',
    },
    {
      id: 'certificate',
      name: '换证明细',
      link: 'certificate',
      parentId: 'uploadWarning',
    },
  ],
  uploadMatch: [
    {
      id: 'collect',
      name: '开票汇总',
      link: 'collect',
      parentId: 'uploadMatch',
    },
    {
      id: 'third',
      name: '三方出库信息',
      link: 'third',
      parentId: 'uploadMatch',
    },
    {
      id: 'settle',
      name: '票据结清',
      link: 'settle',
      parentId: 'uploadMatch',
    },
  ],
  uploadMatch_JF: [
    {
      id: 'collect',
      name: '开票汇总',
      link: 'collect',
      parentId: 'uploadMatch_JF',
    },
    {
      id: 'third',
      name: '解放发车信息',
      link: 'third',
      parentId: 'uploadMatch_JF',
    },
    {
      id: 'settle',
      name: '票据结清',
      link: 'settle',
      parentId: 'uploadMatch_JF',
    },
  ],
  statAnalysis: [
    {
      id: 'expend',
      name: '出账情况',
      link: 'expend',
      parentId: 'statAnalysis',
    },
    {
      id: 'redem',
      name: '赎车情况',
      link: 'redem',
      parentId: 'statAnalysis',
    },
    {
      id: 'shiftA',
      name: '转池情况',
      link: 'shiftA',
      parentId: 'statAnalysis',
    },
    {
      id: 'trade',
      name: '换证情况',
      link: 'trade',
      parentId: 'statAnalysis',
    },
    {
      id: 'return',
      name: '回款情况',
      link: 'return',
      parentId: 'statAnalysis',
    },
  ],
  carChengType: [
    {
      id: 'upload',
      name: '导入',
      link: 'upload',
      parentId: 'carChengType',
    },
    {
      id: 'list',
      name: '导入记录',
      link: 'list',
      parentId: 'carChengType',
    },
  ],
  carSystemType: [
    {
      id: 'upload',
      name: '导入',
      link: 'upload',
      parentId: 'carSystemType',
    },
    {
      id: 'list',
      name: '导入记录',
      link: 'list',
      parentId: 'carSystemType',
    },
  ],
  carReturnType: [
    {
      id: 'upload',
      name: '导入',
      link: 'upload',
      parentId: 'carReturnType',
    },
    {
      id: 'list',
      name: '导入记录',
      link: 'list',
      parentId: 'carReturnType',
    },
  ],
  carSync: [
    {
      id: 'carIn',
      name: '车辆入库',
      link: 'carIn',
      parentId: 'carSync',
    },
    {
      id: 'carOut',
      name: '赎车明细',
      link: 'carOut',
      parentId: 'carSync',
    },
    {
      id: 'carSend',
      name: '发车明细',
      link: 'carSend',
      parentId: 'carSync',
    },
    {
      id: 'carDis',
      name: '经销商列表',
      link: 'carDis',
      parentId: 'carSync',
    },
    {
      id: 'disAccounting',
      name: '经销商出账信息',
      link: 'disAccounting',
      parentId: 'carSync',
    },
    {
      id: 'disExposure',
      name: '单笔业务敞口更新',
      link: 'disExposure',
      parentId: 'carSync',
    },
    {
      id: 'disSettlement',
      name: '单笔业务到期结清',
      link: 'disSettlement',
      parentId: 'carSync',
    },
    {
      id: 'carReturn',
      name: '退货明细',
      link: 'carReturn',
      parentId: 'carSync',
    },
  ],
  marketFirst: [
    {
      id: 'marketFirstList',
      name: '待审核列表',
      link: 'marketFirstList',
      parentId: 'marketFirst',
    },
    {
      id: 'marketFirstAbnormal',
      name: '异常跟踪列表',
      link: 'marketFirstAbnormal',
      parentId: 'marketFirst',
    },
  ],
  marketAwardRemit: [
    {
      id: 'awardRemitTodo',
      name: '待发放列表',
      link: 'awardRemitTodo',
      parentId: 'marketAwardRemit',
    },
    {
      id: 'awardRemitDone',
      name: '已发放列表',
      link: 'awardRemitDone',
      parentId: 'marketAwardRemit',
    },
  ],
  noSupervise: [
    {
      id: 'jieSupervise',
      name: '接车接证',
      link: 'jieSupervise',
      parentId: 'noSupervise',
    },
    {
      id: 'pangSupervise',
      name: '盘车盘证',
      link: 'pangSupervise',
      parentId: 'noSupervise',
    },
  ],
  noSuperviseList: [
    {
      id: 'carList',
      name: '车辆明细',
      link: 'carList',
      parentId: 'noSuperviseList',
    },
    // {
    //   id: 'makeList',
    //   name: '开票信息',
    //   link: 'makeList',
    //   parentId: 'noSuperviseList',
    // },
    {
      id: 'taskList',
      name: '下发任务',
      link: 'taskList',
      parentId: 'noSuperviseList',
    },
  ],
  repaymentAmount: [
    {
      id: 'dealer',
      name: '经销商+品牌+供应链',
      link: 'dealer',
      parentId: 'repaymentAmount',
    },
    {
      id: 'brand',
      name: '品牌情况表',
      link: 'brand',
      parentId: 'repaymentAmount',
    },
    {
      id: 'supplyChain',
      name: '品牌+供应链情况表',
      link: 'supplyChain',
      parentId: 'repaymentAmount',
    },
  ],
  uploadFCZ: [
    {
      id: 'list',
      name: '数据源导入',
      link: 'list',
      parentId: 'uploadFCZ',
    },
    {
      id: 'history',
      name: '导入历史',
      link: 'history',
      parentId: 'uploadFCZ',
    },
  ],
  CarAction_Dis: [
    {
      id: 'carTodo',
      name: '车辆明细上报',
      link: 'carTodo',
      parentId: 'CarAction_Dis',
    },
    {
      id: 'carList',
      name: '发车明细',
      link: 'carList',
      parentId: 'CarAction_Dis',
    },
  ],
};

// export default subMenuMap;
export default menus;
